packages:
  - packages/vite-plugin-ignore-dynamic-imports
  - packages/rollup-plugin
  - packages/core
  - playground
  - tools/icon-processor
  - packages/rollup-plugin/tests/projects/*
catalog:
  "@babel/generator": ^7.27.5
  "@babel/types": ^7.27.6
  "@codemirror/autocomplete": ^6.18.6
  "@codemirror/commands": ^6.8.1
  "@codemirror/language": ^6.11.1
  "@codemirror/lint": ^6.8.5
  "@codemirror/search": ^6.5.11
  "@codemirror/state": ^6.5.2
  "@codemirror/theme-one-dark": ^6.1.2
  "@codemirror/view": ^6.37.1
  "@lezer/common": ^1.2.3
  "@lezer/highlight": ^1.2.1
  "@playwright/experimental-ct-solid": ^1.48.2
  "@replit/codemirror-lang-csharp": ^6.2.0
  "@replit/codemirror-vscode-keymap": ^6.0.2
  "@rollup/pluginutils": ^5.2.0
  "@solid-primitives/scheduled": ^1.5.1
  "@types/argparse": ^2.0.14
  "@types/babel__generator": ^7.27.0
  "@types/node": ^24.0.15
  "@types/tinycolor2": ^1.4.6
  "@vanilla-extract/css": ^1.17.2
  "@vanilla-extract/css-utils": ^0.1.4
  "@vanilla-extract/vite-plugin": ^5.0.3
  "@vitejs/plugin-basic-ssl": ^2.0.0
  "@yukiakai/resolve-package": ^1.0.2
  argparse: ^2.0.1
  clsx: ^2.1.1
  codemirror: ^6.0.1
  comlink: ^4.4.1
  compare-versions: ^6.1.1
  cpy-cli: ^5.0.0
  node-html-parser: ^6.1.12
  normalize.css: ^8.0.1
  postcss-nesting: ^13.0.1
  postcss-scrollbar: ^0.5.1
  prettier: ^3.6.2
  rollup: ^4.41.2
  rollup-plugin-copy: ^3.5.0
  solid-js: ^1.9.7
  tinycolor2: ^1.6.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unplugin-ast: ^0.15.0
  vite-node: ^1.3.0
  vite-plugin-inspect: ^11.1.0
  vite-plugin-solid: ^2.11.6
  vite-plugin-utils: ^0.4.5
  vitefu: ^1.0.6
  vite: ^6.3.5
  vitest: ^3.2.2

