// Copied from https://github.com/dotnet/roslyn/blob/bf788a53760c304429023f40595b4e87196df1fd/src/Workspaces/Core/Portable/Tags/WellKnownTags.cs

export const WellKnownTags = {
  // accessibility
  Public: "Public",
  Protected: "Protected",
  Private: "Private",
  Internal: "Internal",

  // project elements
  File: "File",
  Project: "Project",
  Folder: "Folder",
  Assembly: "Assembly",

  // language elements
  Class: "Class",
  Constant: "Constant",
  Delegate: "Delegate",
  Enum: "Enum",
  EnumMember: "EnumMember",
  Event: "Event",
  ExtensionMethod: "ExtensionMethod",
  Field: "Field",
  Interface: "Interface",
  Intrinsic: "Intrinsic",
  Keyword: "Keyword",
  Label: "Label",
  Local: "Local",
  Namespace: "Namespace",
  Method: "Method",
  Module: "Module",
  Operator: "Operator",
  Parameter: "Parameter",
  Property: "Property",
  RangeVariable: "RangeVariable",
  Reference: "Reference",
  Structure: "Structure",
  TypeParameter: "TypeParameter",

  // other
  Snippet: "Snippet",
  Error: "Error",
  Warning: "Warning",
} as const;

type ToUnion<T> = T[keyof T];
export type WellKnownTag = ToUnion<typeof WellKnownTags>;

export const WellKnownTagArrays = {
  Assembly: [WellKnownTags.Assembly],
  ClassPublic: [WellKnownTags.Class, WellKnownTags.Public],
  ClassProtected: [WellKnownTags.Class, WellKnownTags.Protected],
  ClassPrivate: [WellKnownTags.Class, WellKnownTags.Private],
  ClassInternal: [WellKnownTags.Class, WellKnownTags.Internal],
  ConstantPublic: [WellKnownTags.Constant, WellKnownTags.Public],
  ConstantProtected: [WellKnownTags.Constant, WellKnownTags.Protected],
  ConstantPrivate: [WellKnownTags.Constant, WellKnownTags.Private],
  ConstantInternal: [WellKnownTags.Constant, WellKnownTags.Internal],
  DelegatePublic: [WellKnownTags.Delegate, WellKnownTags.Public],
  DelegateProtected: [WellKnownTags.Delegate, WellKnownTags.Protected],
  DelegatePrivate: [WellKnownTags.Delegate, WellKnownTags.Private],
  DelegateInternal: [WellKnownTags.Delegate, WellKnownTags.Internal],
  EnumPublic: [WellKnownTags.Enum, WellKnownTags.Public],
  EnumProtected: [WellKnownTags.Enum, WellKnownTags.Protected],
  EnumPrivate: [WellKnownTags.Enum, WellKnownTags.Private],
  EnumInternal: [WellKnownTags.Enum, WellKnownTags.Internal],
  EnumMemberPublic: [WellKnownTags.EnumMember, WellKnownTags.Public],
  EnumMemberProtected: [WellKnownTags.EnumMember, WellKnownTags.Protected],
  EnumMemberPrivate: [WellKnownTags.EnumMember, WellKnownTags.Private],
  EnumMemberInternal: [WellKnownTags.EnumMember, WellKnownTags.Internal],
  EventPublic: [WellKnownTags.Event, WellKnownTags.Public],
  EventProtected: [WellKnownTags.Event, WellKnownTags.Protected],
  EventPrivate: [WellKnownTags.Event, WellKnownTags.Private],
  EventInternal: [WellKnownTags.Event, WellKnownTags.Internal],
  ExtensionMethodPublic: [WellKnownTags.ExtensionMethod, WellKnownTags.Public],
  ExtensionMethodProtected: [WellKnownTags.ExtensionMethod, WellKnownTags.Protected],
  ExtensionMethodPrivate: [WellKnownTags.ExtensionMethod, WellKnownTags.Private],
  ExtensionMethodInternal: [WellKnownTags.ExtensionMethod, WellKnownTags.Internal],
  FieldPublic: [WellKnownTags.Field, WellKnownTags.Public],
  FieldProtected: [WellKnownTags.Field, WellKnownTags.Protected],
  FieldPrivate: [WellKnownTags.Field, WellKnownTags.Private],
  FieldInternal: [WellKnownTags.Field, WellKnownTags.Internal],
  InterfacePublic: [WellKnownTags.Interface, WellKnownTags.Public],
  InterfaceProtected: [WellKnownTags.Interface, WellKnownTags.Protected],
  InterfacePrivate: [WellKnownTags.Interface, WellKnownTags.Private],
  InterfaceInternal: [WellKnownTags.Interface, WellKnownTags.Internal],
  Intrinsic: [WellKnownTags.Intrinsic],
  Keyword: [WellKnownTags.Keyword],
  Label: [WellKnownTags.Label],
  Local: [WellKnownTags.Local],
  Namespace: [WellKnownTags.Namespace],
  MethodPublic: [WellKnownTags.Method, WellKnownTags.Public],
  MethodProtected: [WellKnownTags.Method, WellKnownTags.Protected],
  MethodPrivate: [WellKnownTags.Method, WellKnownTags.Private],
  MethodInternal: [WellKnownTags.Method, WellKnownTags.Internal],
  ModulePublic: [WellKnownTags.Module, WellKnownTags.Public],
  ModuleProtected: [WellKnownTags.Module, WellKnownTags.Protected],
  ModulePrivate: [WellKnownTags.Module, WellKnownTags.Private],
  ModuleInternal: [WellKnownTags.Module, WellKnownTags.Internal],
  Folder: [WellKnownTags.Folder],
  Operator: [WellKnownTags.Operator],
  Parameter: [WellKnownTags.Parameter],
  PropertyPublic: [WellKnownTags.Property, WellKnownTags.Public],
  PropertyProtected: [WellKnownTags.Property, WellKnownTags.Protected],
  PropertyPrivate: [WellKnownTags.Property, WellKnownTags.Private],
  PropertyInternal: [WellKnownTags.Property, WellKnownTags.Internal],
  RangeVariable: [WellKnownTags.RangeVariable],
  Reference: [WellKnownTags.Reference],
  StructurePublic: [WellKnownTags.Structure, WellKnownTags.Public],
  StructureProtected: [WellKnownTags.Structure, WellKnownTags.Protected],
  StructurePrivate: [WellKnownTags.Structure, WellKnownTags.Private],
  StructureInternal: [WellKnownTags.Structure, WellKnownTags.Internal],
  TypeParameter: [WellKnownTags.TypeParameter],
  Snippet: [WellKnownTags.Snippet],

  Error: [WellKnownTags.Error],
  Warning: [WellKnownTags.Warning],
} as const;

export type WellKnownTagArray = ToUnion<typeof WellKnownTagArrays>;
