/**
 * Microsoft.CodeAnalysis.TextTags, copied from
 * https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/Common/TextTags.cs
 */
export type TextTag =
  | "Alias"
  | "Assembly"
  | "Class"
  | "Delegate"
  | "Enum"
  | "ErrorType"
  | "Event"
  | "Field"
  | "Interface"
  | "Keyword"
  | "Label"
  | "LineBreak"
  | "NumericLiteral"
  | "StringLiteral"
  | "Local"
  | "Method"
  | "Module"
  | "Namespace"
  | "Operator"
  | "Parameter"
  | "Property"
  | "Punctuation"
  | "Space"
  | "Struct"
  | "AnonymousTypeIndicator"
  | "Text"
  | "TypeParameter"
  | "RangeVariable"
  | "EnumMember"
  | "ExtensionMethod"
  | "Constant"
  | "Record"
  | "RecordStruct"
  | "ContainerStart"
  | "ContainerEnd"
  | "CodeBlockStart"
  | "CodeBlockEnd";
